### ISSUE TITLE
Demo site unavailable?

### ISSUE THREAD

**Issue by cviebrock** [Farkie/tinygrab#2]
Not sure if this is the right place to ask ...

At some point I set my `/etc/hosts` to point tinygrab.com to 212.159.61.116.  Was that your server, Alan?  I think I needed this just to get past the email/password sign-in for the TinyGrab app.

My requests are now showing Laravel error pages, so I'm guessing this IP once hosted a version of your app to make it easy for people to "sign in".

Thanks!

**Comment by Farkie** [comment]
That's not my IP, mines on 5.196.192.209 - let me know if it works :)

**Comment by cviebrock** [comment]
Perfect ... thanks!
